name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  de:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: nx build app
      # - env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release
